import OpenAI from "openai";

export const runtime = "nodejs";

const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const SYSTEM_PROMPT = `You are LiDAR-Bot, an expert AI assistant for a real-time underground sewer monitoring system.
You help operators with:
- Interpreting LiDAR scan results and point-cloud data
- Diagnosing pipe blockages, cracks, and foreign object detection
- Understanding sensor alerts and anomaly reports
- RPLidar A1 sensor configuration, calibration, and maintenance
- Arduino Mega / ESP32 firmware behavior and edge ML classification
- Wi-Fi, LoRa WAN, GSM/LTE, and MQTT communication troubleshooting
- Dashboard metrics, 3D map visualization, and alert management
- Preventive maintenance schedules and inspection recommendations

Always respond in a clear, technical, and concise manner.
If asked something outside sewer monitoring or LiDAR systems, politely redirect to your domain.`;

export async function POST(req) {
  try {
    const body = await req.json();
    const { messages = [], newInput, imageDataURL } = body;

    // ── Validate: must have at least some input ──────────────────────────────
    if (!newInput && !imageDataURL) {
      return new Response(
        JSON.stringify({ error: "No input provided." }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    // ── Build the new user message content ───────────────────────────────────
    const userContent = [];
    if (newInput?.trim()) {
      userContent.push({ type: "text", text: newInput.trim() });
    }
    if (imageDataURL) {
      // If there's an image but no text, add a default prompt so OpenAI doesn't reject
      if (!newInput?.trim()) {
        userContent.push({
          type: "text",
          text: "Analyze this image from the sewer monitoring system.",
        });
      }
      userContent.push({
        type: "image_url",
        image_url: { url: imageDataURL },
      });
    }

    // ── Rebuild conversation history for multi-turn context ───────────────────
    // messages is the prior history from the frontend [ {role, content}, ... ]
    const history = messages
      .filter((m) => m.role === "user" || m.role === "assistant")
      .map((m) => ({
        role: m.role,
        // frontend stores content as a plain string
        content: typeof m.content === "string" ? m.content : JSON.stringify(m.content),
      }));

    const chatMessages = [
      { role: "system", content: SYSTEM_PROMPT },
      ...history,
      { role: "user", content: userContent },
    ];

    // ── Call OpenAI ───────────────────────────────────────────────────────────
    const response = await client.chat.completions.create({
      model: "gpt-4o-mini",
      messages: chatMessages,
      temperature: 0.4,
      max_tokens: 600,
    });

    const reply =
      response.choices?.[0]?.message?.content?.trim() ??
      "[ ERROR ] No response generated by the model.";

    return new Response(JSON.stringify({ reply }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });

  } catch (e) {
    // ── Log the real error server-side for debugging ──────────────────────────
    console.error("[LiDAR Chat API Error]", e?.message, e?.status, e?.error);

    // Return the actual OpenAI error message so you can see it in the frontend
    const message =
      e?.error?.message ||   // OpenAI structured error
      e?.message ||           // JS error
      "Unknown server error";

    return new Response(
      JSON.stringify({ error: message }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
}